### ISSUE TITLE
OutOfRangeException calling wktToFeature

### ISSUE THREAD

**Issue by ParkerPonderosa** [Terradue/DotNetGeoJson#9]
I'm making what I think is a simple call to wktToFeature and I'm getting an OutOfRangeException.
I'm on the latest version, 1.5.7
![version](https://cloud.githubusercontent.com/assets/15988572/12682177/60525206-c66f-11e5-9107-892e431460d3.PNG)

Here is the call:
    var feature = GeometryFactory.WktToFeature(wkt);

[Polygon.txt](https://github.com/Terradue/DotNetGeoJson/files/110087/Polygon.txt)
[exceptionDetails.txt](https://github.com/Terradue/DotNetGeoJson/files/110088/exceptionDetails.txt)

**Comment by emmanuelmathot** [comment]
Thank you for reporting, I'll check that now

**Comment by emmanuelmathot** [comment]
fixed by #10
